apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infrastructure
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/tockertheo/aufgabe_data_eng/
    path: infrastructure
    directory:
      recurse: true
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  annotations:
    argocd.argoproj.io/sync-wave: "4"