apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: minio-input-eventsource
  namespace: argo-events
spec:
  template:
  service:
    ports:
      - port: 12000
        targetPort: 12000

  minio:
    input:                    
      bucket:
        name: input-data
      endpoint: minio.data-storage.svc.cluster.local:9000
      events:
        - s3:ObjectCreated:*
      insecure: true
      accessKey:
        name: minio
        key: root-user
      secretKey:
        name: minio
        key: root-password